# Welcome to Jekyll!
title: HINGTAK LLC., Wire&Cable,Connectors,Wire Harness
email: sales@hingtak.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hingtak
github_username:  ba7lnn

#elative_permailinks: true

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed
#  - jekyll-paginate

show_excerpts: true

gem 'jekyll-paginate', group: :jekyll_plugins

permalink: pretty
plugins:
  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed