# Welcome to Jekyll!
title: HINGTAK LLC., Wire&Cable,Connectors,Wire Harness
email: hingtak@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  DELIVERING THE FUTURE. CONNECTING THE WORLD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hingtak
github_username:  ba7lnn

#elative_permailinks: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate


# paginate: 12
# paginate_path: "/page/:num"
